version: '3'
services:
 registry:
   container_name: docker-registry
   image: registry:2
   ports: 
   - 5000:5000
   volumes:
   - docker-registry-data:/var/lib/registry
volumes:
 docker-registry-data: {}
